### ISSUE TITLE
The `play` command does not pick the correct playlist after a tag search.

### ISSUE THREAD

**Issue by e0i** [dbrgn/orochi#60]
After performing a tag search, the `play n` command plays a playlist that is not listed in the latest search result. It is supposed to play a playlist chosen by its corresponding number.

Example output:

    (8tracks)> search_tags chillwave, electronic
    Results for "chillwave, electronic":
     1)  seven wonders (9 tracks, 0h 29m, by joawia)
         Tags: happy, chillwave, odesza, electronic, majestic casual
     2)  Echoes (8 tracks, 0h 24m, by sziaszia)
         Tags: chillwave, instrumental, 3am, misc, indie electronic
     3)  chillin like a villain (17 tracks, 0h 5m, by alienvxbes)
         Tags: chillwave, chill, electronic, relax, chillstep
     4)  Beam (9 tracks, 0h 33m, by Simple Matters)
         Tags: chillwave, chill vibes, electronic, mellow, feel good
     5)   girls born in the 90’s are dangerous (11 tracks, 0h 34m, by the-glamorous)
         Tags: chill, chillwave, tumblr, electronic, trap
     6)  I'm cool (39 tracks, 2h 13m, by loisbang)
         Tags: indie rock, alt rock, chillwave, indie, electronic
     7)  reverie (9 tracks, 0h 32m, by Hensin)
         Tags: chill, electronic, chillwave, vaporwave, aesthetic
     8)  Illusions (11 tracks, 0h 34m, by Simple Matters)
         Tags: neo-soul, chillwave, electronic, study, feel good vibes
     9)  Rebirthロ (11 tracks, 0h 44m, by PetScoliosis)
         Tags: synthpop, dreampop, chillwave, electronic, alternative
     10) ethereal (9 tracks, 0h 13m, by aoifeey)
         Tags: electronic, chill, chillwave, ambient, relax
    Page 1 on 431. --Next-- (Enter)
    (8tracks)> play 7
    Now playing Bubble Bath by kev. from the album EDM.com Free Downloads.

**Comment by dbrgn** [comment]
I cannot reproduce this:

```
$ orochi
Welcome! Type "help" for more information.
(8tracks)> search_tags chillwave, electronic
Results for "chillwave, electronic":
 1)  seven wonders (9 tracks, 0h 29m, by joawia)
     Tags: happy, chillwave, odesza, electronic, majestic casual
 2)  chillin like a villain (17 tracks, 0h 5m, by alienvxbes)
     Tags: chillwave, chill, electronic, relax, chillstep
 3)  Beam (9 tracks, 0h 33m, by Simple Matters)
     Tags: chillwave, chill vibes, electronic, mellow, feel good
 4)   girls born in the 90’s are dangerous (11 tracks, 0h 34m, by the-glamorous)
     Tags: chill, chillwave, tumblr, electronic, trap
 5)  I'm cool (39 tracks, 2h 13m, by loisbang)
     Tags: indie rock, alt rock, chillwave, indie, electronic
 6)  reverie (9 tracks, 0h 32m, by Hensin)
     Tags: chill, electronic, chillwave, vaporwave, aesthetic
 7)  Illusions (11 tracks, 0h 34m, by Simple Matters)
     Tags: neo-soul, chillwave, electronic, study, feel good vibes
 8)  Rebirthロ (11 tracks, 0h 44m, by PetScoliosis)
     Tags: synthpop, dreampop, chillwave, electronic, alternative
 9)  ethereal (9 tracks, 0h 13m, by aoifeey)
     Tags: electronic, chill, chillwave, ambient, relax
 10) late night chills (12 tracks, 0h 42m, by prim.p)
     Tags: chill, chillwave, electronic, female vocalists, high
Page 1 on 424. --Next-- (Enter)
(8tracks)> play 7
Now playing No Diggity (Remake) by Namuuna. from the album No Diggity.
(8tracks:Illusions)> stop
Stopping playback...
play(8tracks)> play 6
Now playing Bubble Bath by kev. from the album EDM.com Free Downloads.
(8tracks:reverie)> stop
Stopping playback...
```

You can see the chosen playlist in the status line after the "now playing" lines.

**Comment by dbrgn** [comment]
Actually I think your example is correct behavior too. "Bubble Bath" is actually a song in the "reverie" playlist. If you disagree, please let me know :)

**Comment by e0i** [comment]
After reading your response I realized that I was confused because the playlist name somehow didn't show up inside parentheses. Like, `(8tracks)>` instead of `(8tracks:reverie)>`.
Thanks for the reply.
